### ISSUE TITLE
Android Build Error

### ISSUE THREAD

**Issue by EliasDeuss** [spencerccf/app_settings#19] opened 2019-10-24 07:43 UTC
```
FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Execution failed for task ':app_settings:verifyReleaseResources'.                                                  
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/elias/Documents/GitHub/isontic-Education/build/app_settings/intermediates/res/merged/release/values/values.xml:236: error: resource android:attr/fontVariationSettings not found.
  /Users/elias/Documents/GitHub/isontic-Education/build/app_settings/intermediates/res/merged/release/values/values.xml:237: error: resource android:attr/ttcIndex not found.
  error: failed linking references.         
```

**Comment by spencerccf** [comment] 2019-10-29 13:28
Could you try running with verbose mode on "-v" to get more details on this error?

**Comment by saravananmnm** [comment] 2019-11-01 12:31
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app_settings:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\merged\release\values\values.xml:186: error: resource android:attr/fontVariationSettings not found.
  C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\merged\release\values\values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\Admin\.gradle\caches\transforms-2\files-2.1\e3127b8be5bc66583a71cdff03aa2c8f\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Admin\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\aapt_friendly_merged_manifests\release\processReleaseManifest\aapt\AndroidManifest.xml\
          -o\
          C:\Users\Admin\AppData\Local\Temp\aapt-8173774860643341813-out\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-hdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-hdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-hdpi-v4_notification_bg_normal.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-hdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-hdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-mdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-mdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-mdpi-v4_notification_bg_normal.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-mdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-mdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-v21_notification_action_background.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-xhdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-xhdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-xhdpi-v4_notification_bg_normal.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-xhdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-xhdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable_notification_bg.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable_notification_bg_low.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable_notification_icon_background.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable_notification_tile_bg.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout-v16_notification_template_custom_big.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout-v21_notification_action.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout-v21_notification_action_tombstone.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout-v21_notification_template_custom_big.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout-v21_notification_template_icon_group.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout_notification_action.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout_notification_action_tombstone.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout_notification_template_icon_group.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout_notification_template_part_chronometer.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout_notification_template_part_time.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-af_values-af.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-am_values-am.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ar_values-ar.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-as_values-as.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-az_values-az.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-b+sr+Latn_values-b+sr+Latn.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-be_values-be.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-bg_values-bg.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-bn_values-bn.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-bs_values-bs.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ca_values-ca.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-cs_values-cs.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-da_values-da.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-de_values-de.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-el_values-el.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-en-rAU_values-en-rAU.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-en-rCA_values-en-rCA.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-en-rGB_values-en-rGB.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-en-rIN_values-en-rIN.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-en-rXC_values-en-rXC.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-es-rUS_values-es-rUS.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-es_values-es.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-et_values-et.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-eu_values-eu.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-fa_values-fa.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-fi_values-fi.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-fr-rCA_values-fr-rCA.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-fr_values-fr.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-gl_values-gl.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-gu_values-gu.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-hi_values-hi.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-hr_values-hr.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-hu_values-hu.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-hy_values-hy.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-in_values-in.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-is_values-is.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-it_values-it.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-iw_values-iw.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ja_values-ja.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ka_values-ka.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-kk_values-kk.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-km_values-km.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-kn_values-kn.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ko_values-ko.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ky_values-ky.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-lo_values-lo.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-lt_values-lt.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-lv_values-lv.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-mk_values-mk.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ml_values-ml.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-mn_values-mn.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-mr_values-mr.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ms_values-ms.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-my_values-my.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-nb_values-nb.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ne_values-ne.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-nl_values-nl.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-or_values-or.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-pa_values-pa.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-pl_values-pl.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-pt-rBR_values-pt-rBR.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-pt-rPT_values-pt-rPT.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-pt_values-pt.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ro_values-ro.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ru_values-ru.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-si_values-si.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-sk_values-sk.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-sl_values-sl.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-sq_values-sq.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-sr_values-sr.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-sv_values-sv.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-sw_values-sw.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ta_values-ta.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-te_values-te.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-th_values-th.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-tl_values-tl.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-tr_values-tr.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-uk_values-uk.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ur_values-ur.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-uz_values-uz.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-v16_values-v16.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-v21_values-v21.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-vi_values-vi.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-zh-rCN_values-zh-rCN.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-zh-rHK_values-zh-rHK.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-zh-rTW_values-zh-rTW.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-zu_values-zu.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values_values.arsc.flat\
          --auto-add-overlay\
          --non-final-ids\
          -0\
          apk\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 39s

**Comment by saravananmnm** [comment] 2019-11-01 12:32
Same issue while build apk..

[√] Flutter (Channel master, v1.10.15-pre.137, on Microsoft Windows [Version 10.0.18362.418], locale en-IN)
    • Flutter version 1.10.15-pre.137 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision b9817b4f59 (2 weeks ago), 2019-10-15 17:36:34 -0700
    • Engine revision 540fc977bb
    • Dart version 2.6.0 (build 2.6.0-dev.7.0 70a7ef3f58)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (3 available)
    • Genymotion      • 192.168.34.101:5555 • android-x86    • Android 9 (API 28)
    • Chrome          • chrome              • web-javascript • Google Chrome 77.0.3865.120
    • Headless Server • headless-server     • web-javascript • Flutter Tools

• No issues found!

**Comment by spencerccf** [comment] 2019-11-05 21:04
Is your project using Kotlin or Java?

**Comment by nguyenhuutinh** [comment] 2019-11-08 05:11
try to change the compileSdkVersion to: `compileSdkVersion 28`

**Comment by nihalreddy33** [comment] 2019-11-08 11:34
Even I am facing the same issue with compileSdkVersion 28 & my Project is using Java.

**Comment by spencerccf** [comment] 2019-11-09 14:46
This plugin only supports Kotlin... no support for Java at this time.

**Comment by spencerccf** [comment] 2019-11-20 20:51
I was able to create a sample Flutter project using Java for Android and the plugin works properly.  I'm not able to reproduce the compile error you are getting.  I used Galaxy with API 28 and it's working fine.  Can you update to latest plugin version: 2.0.1+1 and give it another try.

**Closed** 2019-11-20 22:30 UTC
