### ISSUE TITLE
Gradle Version Error

### ISSUE THREAD

**Issue by qiuqimin** [spencerccf/app_settings#32] opened 2019-12-20 09:36 UTC
# gradle
```
classpath 'com.android.tools.build:gradle:3.5.3'
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
```
# flutter doctor
Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
# Error Log
```
* What went wrong:
A problem occurred evaluating root project 'app_settings'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.6. If using the gradle wrapper, try editing the distributionUrl in C:\Users\Qiu\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\app_se
ttings-3.0.0+1\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip
```

**Comment by spencerccf** [comment] 2019-12-20 19:50
Is your current Gradle version in your project set to: 5.4.1 ?

**Comment by saravananmnm** [comment] 2020-01-09 09:58
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'app_settings'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by saravananmnm** [comment] 2020-01-09 09:59
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!

**Comment by spencerccf** [comment] 2020-01-09 16:13
@saravananmnm  I will look into this.  Have you tried clearing your cached files to perform a fresh build?

Thanks

**Comment by maxlapides** [comment] 2020-01-16 04:13
I was experiencing the same error. Then I scrolled up in my logs and discovered that because I had forgotten to escape an apostrophe in an `res/values` XML file, the build failed with this error first:

```
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
```

Then I got the error originally posted in this thread:

```
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.6. If using the gradle wrapper, try editing the distributionUrl in /Users/maxlapides/flutter/.pub-cache/hosted/pub.dartlang.org/app_settings-3.0.0+1/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip
```

So initially I thought `app_settings` was responsible, but turns out it wasn't actually the root cause of my issue.

**Comment by spencerccf** [comment] 2020-02-22 16:53
@saravananmnm did @maxlapides input help solve your issue?

**Comment by saravananmnm** [comment] 2020-02-25 06:28
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app_settings:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\merged\release\values\values.xml:186: error: resource android:attr/fontVariationSettings not found.
  C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\merged\release\values\values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\Admin\.gradle\caches\transforms-2\files-2.1\e3127b8be5bc66583a71cdff03aa2c8f\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Admin\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\aapt_friendly_merged_manifests\release\processReleaseManifest\aapt\AndroidManifest.xml\
          -o\
          C:\Users\Admin\AppData\Local\Temp\aapt-2738175658657562854-out\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-hdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-hdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-hdpi-v4_notification_bg_normal.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-hdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-hdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-mdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-mdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-mdpi-v4_notification_bg_normal.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-mdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-mdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-v21_notification_action_background.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-xhdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-xhdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-xhdpi-v4_notification_bg_normal.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-xhdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable-xhdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable_notification_bg.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable_notification_bg_low.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable_notification_icon_background.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\drawable_notification_tile_bg.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout-v16_notification_template_custom_big.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout-v21_notification_action.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout-v21_notification_action_tombstone.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout-v21_notification_template_custom_big.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout-v21_notification_template_icon_group.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout_notification_action.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout_notification_action_tombstone.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout_notification_template_icon_group.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout_notification_template_part_chronometer.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\layout_notification_template_part_time.xml.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-af_values-af.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-am_values-am.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ar_values-ar.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-as_values-as.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-az_values-az.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-b+sr+Latn_values-b+sr+Latn.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-be_values-be.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-bg_values-bg.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-bn_values-bn.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-bs_values-bs.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ca_values-ca.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-cs_values-cs.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-da_values-da.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-de_values-de.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-el_values-el.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-en-rAU_values-en-rAU.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-en-rCA_values-en-rCA.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-en-rGB_values-en-rGB.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-en-rIN_values-en-rIN.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-en-rXC_values-en-rXC.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-es-rUS_values-es-rUS.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-es_values-es.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-et_values-et.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-eu_values-eu.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-fa_values-fa.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-fi_values-fi.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-fr-rCA_values-fr-rCA.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-fr_values-fr.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-gl_values-gl.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-gu_values-gu.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-hi_values-hi.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-hr_values-hr.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-hu_values-hu.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-hy_values-hy.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-in_values-in.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-is_values-is.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-it_values-it.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-iw_values-iw.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ja_values-ja.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ka_values-ka.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-kk_values-kk.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-km_values-km.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-kn_values-kn.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ko_values-ko.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ky_values-ky.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-lo_values-lo.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-lt_values-lt.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-lv_values-lv.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-mk_values-mk.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ml_values-ml.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-mn_values-mn.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-mr_values-mr.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ms_values-ms.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-my_values-my.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-nb_values-nb.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ne_values-ne.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-nl_values-nl.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-or_values-or.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-pa_values-pa.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-pl_values-pl.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-pt-rBR_values-pt-rBR.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-pt-rPT_values-pt-rPT.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-pt_values-pt.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ro_values-ro.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ru_values-ru.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-si_values-si.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-sk_values-sk.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-sl_values-sl.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-sq_values-sq.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-sr_values-sr.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-sv_values-sv.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-sw_values-sw.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ta_values-ta.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-te_values-te.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-th_values-th.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-tl_values-tl.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-tr_values-tr.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-uk_values-uk.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-ur_values-ur.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-uz_values-uz.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-v16_values-v16.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-v21_values-v21.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-vi_values-vi.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-zh-rCN_values-zh-rCN.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-zh-rHK_values-zh-rHK.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-zh-rTW_values-zh-rTW.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values-zu_values-zu.arsc.flat\
          -R\
          C:\Saravanan\i-eX_Driver\iex_driver\build\app_settings\intermediates\res\compiled\release\values_values.arsc.flat\
          --auto-add-overlay\
          --non-final-ids\
          -0\
          apk\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 10s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     192.6s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin app_settings...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                   21.7s
Starting a Gradle Daemon, 2 busy Daemons could not be reused, use --status for details
WARNING: The option setting 'android.enableR8=true' is experimental and unsupported.
The current default is 'false'
Consider disabling R8 by removing 'android.enableR8=true' from your gradle.properties before publishing your app.


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'app_settings'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s


The plugin app_settings could not be built due to the issue above.

**Comment by saravananmnm** [comment] 2020-02-25 06:31
Somebody help to resolve this issue.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.657], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by plinkos** [comment] 2020-02-26 00:36
@saravananmnm I’ve not seen this error before.  In looking that the error details is looks like this is the fix:   

Consider disabling R8 by removing 'android.enableR8=true' from your gradle.properties before publishing your app.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by boskokg** [comment] 2020-02-29 13:44
This issue happens when enableR8 is false and enableJetifier is false. When enableJetifier is true this issue is not reproduced.
Can maintainer support build when  enableJetifier is false?

I suppose plugin should have correction for distributionUrl in android/gradle/wrapper/graddle-wrapper.properties:
current:
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
new:
distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-all.zip

**Comment by spencerccf** [comment] 2020-05-26 14:53
@saravananmnm  Setting `android.enableJetifier=true` is required for running AndroidX.  Please update your gradle.properties and that should get you up and running.

**Closed by spencerccf** 2020-05-26 14:53 UTC
